# netlify.toml

# ===============================================
# Configuracion de las Funciones (Ruta de tu Backend)
# ===============================================
[functions]
  # Indica la carpeta donde se encuentra tu c√≥digo Node.js
  directory = "netlify/functions"